class IntBPTree:
    def __init__(self, t: int, filename: str) -> None: ...
    def insert(self, key: int) -> None: ...
    def search(self, key: int) -> bool: ...
    def save(self) -> None: ...
    def load(self) -> None: ...


class StringBPTree:
    def __init__(self, t: int, filename: str) -> None: ...
    def insert(self, key: str) -> None: ...
    def search(self, key: str) -> bool: ...
    def save(self) -> None: ...
    def load(self) -> None: ...
